/**
 * The onboarding flow — 32 screens, in order.
 *
 * Screens 1–30 follow Docs/onboarding/TripNode_Onboarding_Flow.md. Screen 31
 * (`trial-intro`) is a TripNode-Premium teaser whose CTA simply advances —
 * the real RevenueCat paywall lives at /paywall and is shown post-signup.
 * Screen 32 (`permissions`) asks for notification access and finishes onboarding.
 *
 * `*asterisks*` wrap an accented word. `{name}` / `{destination}` are tokens.
 */

import type { OnboardingStep } from './types';

export const ONBOARDING_FLOW: OnboardingStep[] = [
  // ── ACT 1 — INTRODUCTION ─────────────────────────────────────────
  {
    id: 'hook',
    screen: 1,
    type: 'statement',
    headline: 'where to *next*?',
    advance: 'tap',
    showProgress: false,
  },
  {
    id: 'problem-1',
    screen: 2,
    type: 'statement',
    headline: 'planning a trip shouldn’t feel like a *second job*.',
    body: [
      '15 tabs open. 3 conflicting blogs.',
      'a budget that makes sense until you’re actually there.',
      'sound familiar?',
    ],
    advance: 'tap',
  },
  {
    id: 'problem-2',
    screen: 3,
    type: 'statement',
    headline: 'you want to *explore* — not research.',
    body: [
      'but without a real plan, you waste time, overspend, and miss the places that actually matter.',
    ],
    advance: 'tap',
  },
  {
    id: 'solution',
    screen: 4,
    type: 'statement',
    headline: 'TripNode plans your entire trip in *seconds*.',
    body: [
      'tell us where, when, and what you love. our AI builds a day-by-day itinerary — timed, budgeted, and mapped.',
    ],
    advance: 'tap',
  },
  {
    id: 'identity-name',
    screen: 5,
    type: 'textInput',
    headline: 'first things first',
    subheading: 'what should we call you?',
    placeholder: 'Your name',
    field: 'userName',
    minChars: 1,
    autoCapitalize: 'words',
    cta: 'continue',
  },
  {
    id: 'identity-reaction',
    screen: 6,
    type: 'statement',
    headline: 'nice to meet you, *{name}*.',
    subheading: 'let’s figure out how you travel.',
    emoji: '✈️',
    advance: 'auto',
    autoMs: 1800,
  },
  {
    id: 'bombshell-q',
    screen: 7,
    type: 'choice',
    headline: 'how do you usually plan a trip?',
    subheading: 'be honest.',
    mode: 'single',
    layout: 'list',
    field: 'planHabit',
    cta: 'continue',
    options: [
      { value: 'scroll TikTok and Instagram for hours', label: 'scroll TikTok and Instagram for hours', emoji: '📱' },
      { value: 'open 15 browser tabs and hope for the best', label: 'open 15 browser tabs and hope for the best', emoji: '🔍' },
      { value: "copy someone else's itinerary", label: "copy someone else's itinerary", emoji: '📋' },
      { value: 'pay a tour guide to figure it out', label: 'pay a tour guide to figure it out', emoji: '💸' },
      { value: 'honestly? I just wing it', label: 'honestly? I just wing it', emoji: '🤷' },
    ],
  },
  {
    id: 'bombshell-reveal',
    screen: 8,
    type: 'statement',
    headline: '*{name}*, the average traveler spends *9 hours* planning a single trip.',
    body: [
      '9 hours researching places that are closed when you arrive.',
      'budgets that don’t add up until you’re already there.',
      'itineraries copied from strangers who travel nothing like you.',
      'what if those 9 hours became 2 minutes?',
    ],
    advance: 'tap',
  },
  {
    id: 'bridge',
    screen: 9,
    type: 'statement',
    headline: 'it doesn’t have to be *this way*.',
    body: [
      'what if you just picked a place — and a complete, personalized plan appeared?',
      'let’s find out what kind of traveler you are. it takes less than a minute.',
    ],
    advance: 'tap',
  },
  {
    id: 'qb-priorities',
    screen: 10,
    type: 'choice',
    headline: 'what matters most to you when you travel?',
    subheading: 'choose up to 3',
    mode: 'multi',
    maxSelect: 3,
    layout: 'chips',
    multiField: 'priorities',
    cta: 'continue',
    options: [
      { value: 'eating where the locals eat', label: 'Local food', emoji: '🍜' },
      { value: 'jaw-dropping photo spots', label: 'Photo spots', emoji: '📸' },
      { value: 'history and culture that gives you chills', label: 'Culture', emoji: '🏛️' },
      { value: 'doing absolutely nothing on a beautiful beach', label: 'Beach', emoji: '🏖️' },
      { value: 'nightlife and energy', label: 'Nightlife', emoji: '🎉' },
      { value: 'getting off the beaten path', label: 'Off the path', emoji: '🥾' },
      { value: 'wellness and recharging', label: 'Wellness', emoji: '💆' },
      { value: 'shopping and markets', label: 'Shopping', emoji: '🛍️' },
    ],
  },
  {
    id: 'qb-problem',
    screen: 11,
    type: 'choice',
    headline: 'what usually goes wrong on your trips?',
    mode: 'single',
    layout: 'list',
    field: 'tripProblem',
    cta: 'continue',
    options: [
      { value: 'I always blow my budget', label: 'I always blow my budget', emoji: '💸' },
      { value: 'I waste time at overhyped tourist traps', label: 'I waste time at overhyped tourist traps', emoji: '⏰' },
      { value: "I miss the best spots because I didn't plan enough", label: 'I miss the best spots because I didn’t plan enough', emoji: '🗺️' },
      { value: 'I over-plan and it stops being fun', label: 'I over-plan and it stops being fun', emoji: '😫' },
      { value: 'I wing it and regret it later', label: 'I wing it and regret it later', emoji: '🤷' },
    ],
  },
  {
    id: 'reflection-goals',
    screen: 12,
    type: 'reflection',
    variant: 'goals',
    cta: 'continue',
  },
  {
    id: 'qb-budget',
    screen: 13,
    type: 'choice',
    headline: 'what’s your travel budget style?',
    mode: 'single',
    layout: 'list',
    field: 'budgetStyle',
    cta: 'continue',
    options: [
      { value: 'backpacker — every dollar counts', label: 'backpacker — every dollar counts', emoji: '🎒' },
      { value: 'balanced — smart spending, no skimping on experiences', label: 'balanced — smart spending', emoji: '⚖️' },
      { value: "comfort — I'll pay more for less hassle", label: 'comfort — pay more for less hassle', emoji: '💎' },
      { value: "YOLO — I'll worry about it when I get home", label: 'YOLO — worry about it later', emoji: '🤑' },
    ],
  },
  {
    id: 'qb-missed',
    screen: 14,
    type: 'choice',
    headline:
      'have you ever come home from a trip feeling like you missed the best parts?',
    mode: 'single',
    layout: 'list',
    yesNoField: 'missedBest',
    cta: 'continue',
    options: [
      { value: 'yes', label: 'yes — more times than I’d like to admit' },
      { value: 'no', label: 'no — but I’m always afraid I will' },
    ],
  },
  {
    id: 'reflection-emotional',
    screen: 15,
    type: 'reflection',
    variant: 'emotional',
    cta: 'continue',
  },
  {
    id: 'insight-cards',
    screen: 16,
    type: 'reflection',
    variant: 'insightCards',
    cta: 'continue',
  },
  {
    id: 'insight-chart',
    screen: 17,
    type: 'insightChart',
    headline: 'smart planning changes *everything*.',
    caption: '{name}, that could be you.',
    cta: 'learn how TripNode works',
  },

  // ── ACT 2 — CLIMAX ───────────────────────────────────────────────
  {
    id: 'how-it-works',
    screen: 18,
    type: 'howItWorks',
    title: 'how it works',
    steps: [
      'pick a destination, dates, and interests',
      'AI generates your full itinerary — every stop scheduled and costed',
      'review, customize, and go — with maps built in',
    ],
    footer: 'from idea to itinerary, faster than you’d book a restaurant.',
    cta: 'try it now',
    showProgress: false,
  },
  {
    id: 'experience-input',
    screen: 19,
    type: 'textInput',
    headline: 'let’s plan a quick trip, *{name}*.',
    subheading: 'pick a destination — anywhere in the world.',
    placeholder: 'e.g. Tokyo, Bali, Paris…',
    field: 'destination',
    minChars: 2,
    autoCapitalize: 'words',
    cta: 'generate my trip',
  },
  {
    id: 'experience-loading',
    screen: 20,
    type: 'loading',
    caption: 'planning your trip to {destination}…',
    steps: [
      'finding the best spots…',
      'building your day-by-day schedule…',
      'optimizing for time and budget…',
      'mapping your route…',
    ],
    durationMs: 2600,
    tint: 'dark',
    showProgress: false,
    task: 'previewItinerary',
  },
  {
    id: 'experience-itinerary',
    screen: 21,
    type: 'itinerary',
    cta: 'save this trip',
  },
  {
    id: 'congrats',
    screen: 22,
    type: 'congrats',
    cta: 'continue',
  },
  {
    id: 'streak',
    screen: 23,
    type: 'streak',
    cta: 'continue',
  },

  // ── ACT 3 — CONCLUSION ───────────────────────────────────────────
  {
    id: 'plan-loading',
    screen: 24,
    type: 'loading',
    steps: [
      'analyzing your travel style…',
      'matching destinations to your interests…',
      'calibrating budget recommendations…',
      'building your personalized travel plan…',
    ],
    durationMs: 3200,
    tint: 'blue',
    showProgress: false,
  },
  {
    id: 'plan-ready',
    screen: 25,
    type: 'planReady',
    cta: 'see my plan',
    showProgress: false,
  },
  {
    id: 'snapshot',
    screen: 26,
    type: 'snapshot',
    cta: 'continue',
  },
  {
    id: 'commitment-q',
    screen: 27,
    type: 'choice',
    headline: 'so *{name}* — how committed are you to making your next trip unforgettable?',
    mode: 'single',
    layout: 'list',
    field: 'commitment',
    cta: 'continue',
    options: [
      { value: 'Extremely Committed', label: 'Extremely Committed', emoji: '🔥' },
      { value: 'Very Committed', label: 'Very Committed', emoji: '💪' },
      { value: 'Somewhat Committed', label: 'Somewhat Committed', emoji: '🤔' },
      { value: 'A Little Committed', label: 'A Little Committed', emoji: '🌱' },
      { value: 'Just Trying It Out', label: 'Just Trying It Out', emoji: '🪄' },
    ],
  },
  {
    id: 'commitment-response',
    screen: 28,
    type: 'dynamicStatement',
    source: 'commitment',
    cta: 'done',
  },
  {
    id: 'plan-reveal',
    screen: 29,
    type: 'planReveal',
    cta: 'start planning',
  },
  {
    id: 'social-proof',
    screen: 30,
    type: 'socialProof',
    cta: 'join TripNode',
  },
  {
    id: 'trial-intro',
    screen: 31,
    type: 'trialIntro',
    headline: 'Everything you need to travel smart.',
    subheading: 'Built for the way you actually plan.',
    features: [
      {
        icon: 'sparkles-outline',
        title: 'Unlimited AI itineraries',
        subtitle: 'Plan every trip in seconds',
      },
      {
        icon: 'cloud-offline-outline',
        title: 'Offline travel guides',
        subtitle: 'Your plan, even without Wi-Fi',
      },
      {
        icon: 'chatbubble-ellipses-outline',
        title: 'Priority support',
        subtitle: 'Answers when you need them',
      },
      {
        icon: 'shield-checkmark-outline',
        title: 'Ad-free experience',
        subtitle: 'Pure travel, no distractions',
      },
    ],
    reassurance: 'No charge right now',
    cta: 'Try for $0.00',
  },
  {
    id: 'permissions',
    screen: 32,
    type: 'permissions',
    cta: 'Enable reminders',
  },
];

export const ONBOARDING_TOTAL = ONBOARDING_FLOW.length;
